export const TEMPLATES = [
  { id: "executive", name: "Executive Elite", color: "#1e293b", accent: "#eab308" },
  { id: "professional", name: "Global Professional", color: "#0f172a", accent: "#38bdf8" },
  { id: "classic", name: "Heritage Classic", color: "#334155", accent: "#94a3b8" },
  { id: "modern", name: "Modern Minimal", color: "#2563eb", accent: "#60a5fa" },
  { id: "corporate", name: "Corporate Standard", color: "#134e4a", accent: "#2dd4bf" },
  { id: "luxe", name: "Premium Luxe", color: "#171717", accent: "#fbbf24" },
  { id: "minimal", name: "Pure Essence", color: "#18181b", accent: "#a1a1aa" },
  { id: "tech", name: "IT Professional", color: "#164e63", accent: "#22d3ee" },
  { id: "academic", name: "Academic", color: "#0369a1", accent: "#0ea5e9" },
  { id: "clean", name: "Clean", color: "#15803d", accent: "#22c55e" },
  { id: "bold", name: "Bold", color: "#be123c", accent: "#f43f5e" },
  { id: "elegant", name: "Elegant", color: "#4c1d95", accent: "#7c3aed" },
  { id: "contemporary", name: "Contemporary", color: "#155e75", accent: "#06b6d4" },
  { id: "minimalist", name: "Minimalist", color: "#18181b", accent: "#71717a" },
  { id: "stylish", name: "Stylish", color: "#831843", accent: "#db2777" },
  { id: "ocean", name: "Ocean", color: "#0284c7", accent: "#38bdf8" },
  { id: "sunset", name: "Sunset", color: "#ea580c", accent: "#fb923c" },
  { id: "monochrome", name: "Monochrome", color: "#171717", accent: "#525252" },
  { id: "startup", name: "Startup", color: "#059669", accent: "#34d399" },
  { id: "editorial", name: "Editorial", color: "#0c4a6e", accent: "#0ea5e9" },
  { id: "serenity", name: "Serenity", color: "#8b5cf6", accent: "#f5f3ff" },
  // Professional Designs (Proper Resume Designs)
  { id: "vanguard", name: "Vanguard Executive", color: "#111827", accent: "#3b82f6" },
  { id: "horizon", name: "Horizontal Elite", color: "#1f2937", accent: "#10b981" },
  { id: "apex", name: "Apex Lead", color: "#374151", accent: "#f59e0b" },
  { id: "stark", name: "Stark Professional", color: "#000000", accent: "#ffffff" },
  { id: "slate", name: "Slate Corporate", color: "#475569", accent: "#94a3b8" },
  { id: "navy", name: "Deep Navy", color: "#1e3a8a", accent: "#bfdbfe" },
  { id: "emerald", name: "Emerald Growth", color: "#064e3b", accent: "#34d399" },
  { id: "ruby", name: "Ruby Specialist", color: "#7f1d1d", accent: "#f87171" },
  { id: "indigo", name: "Indigo Flow", color: "#312e81", accent: "#818cf8" },
  { id: "charcoal", name: "Charcoal Business", color: "#1f2937", accent: "#6b7280" },
  { id: "platinum", name: "Platinum Standard", color: "#e2e8f0", accent: "#1e293b" },
  { id: "forest", name: "Forest Management", color: "#065f46", accent: "#6ee7b7" },
  { id: "midnight", name: "Midnight Pro", color: "#020617", accent: "#6366f1" },
  { id: "coffee", name: "Roast Coffee", color: "#451a03", accent: "#d97706" },
  { id: "graphite", name: "Graphite Tech", color: "#111827", accent: "#4b5563" },
  { id: "royal", name: "Royal Sovereign", color: "#1e1b4b", accent: "#c084fc" },
  { id: "titan", name: "Titan Industrial", color: "#27272a", accent: "#a1a1aa" },
  { id: "marble", name: "White Marble", color: "#f8fafc", accent: "#0f172a" },
  { id: "copper", name: "Copper Craft", color: "#7c2d12", accent: "#fb923c" },

  // Creative Designs
  { id: "neon", name: "Neon Cyber", color: "#000000", accent: "#22d3ee" },
  { id: "candy", name: "Candy Pop", color: "#db2777", accent: "#f472b6" },
  { id: "galaxy", name: "Interstellar", color: "#0f172a", accent: "#a855f7" },
  { id: "mint", name: "Fresh Mint", color: "#ecfdf5", accent: "#10b981" },
  { id: "gold", name: "Solid Gold", color: "#78350f", accent: "#f59e0b" },
  { id: "lavender", name: "Soft Lavender", color: "#faf5ff", accent: "#a855f7" },
  { id: "sky", name: "Sky High", color: "#f0f9ff", accent: "#0ea5e9" },
  { id: "lemon", name: "Lemon Zest", color: "#fefce8", accent: "#eab308" },
  { id: "rose", name: "Desert Rose", color: "#fff1f2", accent: "#f43f5e" },
  { id: "clay", name: "Terra Cotta", color: "#450a0a", accent: "#ef4444" },
  { id: "vivid", name: "Vivid Pulse", color: "#4338ca", accent: "#facc15" },
  { id: "quartz", name: "Quartz Crystal", color: "#fdf2f8", accent: "#ec4899" },
  { id: "obsidian", name: "Obsidian Dark", color: "#09090b", accent: "#3f3f46" },
  { id: "aurora", name: "Northern Lights", color: "#1e1b4b", accent: "#2dd4bf" },
  { id: "plasma", name: "Plasma Glow", color: "#312e81", accent: "#f43f5e" },
  { id: "retro", name: "Retro Wave", color: "#2d064a", accent: "#f0abfc" },
  { id: "bamboo", name: "Zen Bamboo", color: "#064e3b", accent: "#bef264" },
  { id: "spice", name: "Autumn Spice", color: "#7c2d12", accent: "#f97316" },
  { id: "frost", name: "Arctic Frost", color: "#f0f9ff", accent: "#7dd3fc" },
  { id: "vintage", name: "Sepia Vintage", color: "#422006", accent: "#a16207" },
  { id: "carbon", name: "Carbon Fiber", color: "#0a0a0a", accent: "#d1d5db" },
];

export const getTemplate = (id) => TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
